import './assets/scss/base.scss';

import { createApp } from 'vue';
import { createPinia } from 'pinia';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
// import '@/assets/icon/iconfont.css';
import Dialog from './components/Dialog.vue';
import Cover from './components/Cover.vue';
import Avatar from './components/Avatar.vue';
import VideoItem from './components/VideoItem.vue';
import App from './App.vue';
import router from './router';
import Verify from './utils/Verify';
import request from './utils/Request';
import Message from './utils/Message';
import Confirm from './utils/Confirm';
import { Api } from './utils/Api';
import Utils from './utils/Utils';

const app = createApp(App);
app.use(ElementPlus);
app.component('Dialog', Dialog);
app.component('Cover', Cover);
app.component('Avatar', Avatar);
app.component('VideoItem', VideoItem);
app.use(createPinia());
app.use(router);
app.config.globalProperties.bodyMaxWidth = 2000;
app.config.globalProperties.bodyMinWidth = 1250;

app.config.globalProperties.Verify = Verify;
app.config.globalProperties.request = request;
app.config.globalProperties.Message = Message;
app.config.globalProperties.Confirm = Confirm;
app.config.globalProperties.Api = Api;
app.config.globalProperties.Utils = Utils;
app.config.globalProperties.rowCategoryCount = 10;
app.config.globalProperties.imageThumbnailSuffix = '_thumbnail.jpg';
app.config.globalProperties.bodyPadding=150;
app.config.globalProperties.carouselMaxCount=5;
app.config.globalProperties.imageAccept=".jpg,.png,.gif,.bmp,.webp";
app.config.globalProperties.videoAccept=".mp4,.avi,.rmvb,.mkv,.mov";
app.config.globalProperties.chunkSize=1024*512;
app.config.globalProperties.maxUploading=1;
app.mount('#app');
